{
 "title": "Smart_meter",
 "description": "Smart meter data visulisation",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Electric meter reading",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_electric_metering_current_summation_delivered_watthours_total{}/1000"
    }
   ]
  },
  {
   "title": "gas meter reading",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_gas_metering_current_summation_delivered_m3_total"
    }
   ]
  },
  {
   "title": "Electric cost in current billing period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_electric_metering_bill_to_date_delivered{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Electicity used today",
   "type": "stat",
   "description": "Calculated from meter reading",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(smart_meter_electric_metering_current_summation_delivered_watthours_total{}[$__range])",
     "legendFormat": "smart meter"
    }
   ]
  },
  {
   "title": "Gas cost in current billing period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_gas_metering_bill_to_date_delivered{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas used today",
   "type": "stat",
   "description": "Calculated from meter reading",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(smart_meter_gas_metering_current_summation_delivered_m3_total{}[$__range])",
     "legendFormat": "smart meter"
    }
   ]
  },
  {
   "title": "Current power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_electric_metering_instantaneous_demand_watts{}",
     "legendFormat": "smart meter"
    }
   ]
  },
  {
   "title": "usage over time (as reported by smart meter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "current Electric use",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_electric_metering_current_day_consumption_delivered_watthours",
     "legendFormat": "today"
    },
    {
     "expr": "smart_meter_electric_metering_current_week_consumption_delivered_watthours",
     "legendFormat": "this week"
    },
    {
     "expr": "smart_meter_electric_metering_current_month_consumption_delivered_watthours",
     "legendFormat": "this month"
    }
   ]
  },
  {
   "title": "current gas use",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_gas_metering_current_day_alternative_consumption_delivered_watthours",
     "legendFormat": "today"
    },
    {
     "expr": "smart_meter_gas_metering_current_week_alternative_consumption_delivered_watthours",
     "legendFormat": "this week"
    },
    {
     "expr": "smart_meter_gas_metering_current_month_alternative_consumption_delivered_watthours",
     "legendFormat": "this month"
    }
   ]
  },
  {
   "title": "current Electric cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_electric_prepayment_current_day_cost_consumption_delivered",
     "legendFormat": "today"
    },
    {
     "expr": "smart_meter_electric_prepayment_current_week_cost_consumption_delivered",
     "legendFormat": "this week"
    },
    {
     "expr": "smart_meter_electric_prepayment_current_month_cost_consumption_delivered",
     "legendFormat": "this month"
    }
   ]
  },
  {
   "title": "current gas cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_gas_prepayment_current_day_cost_consumption_delivered",
     "legendFormat": "today"
    },
    {
     "expr": "smart_meter_gas_prepayment_current_week_cost_consumption_delivered",
     "legendFormat": "this week"
    },
    {
     "expr": "smart_meter_gas_prepayment_current_month_cost_consumption_delivered",
     "legendFormat": "this month"
    }
   ]
  },
  {
   "title": "historic electric use",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_electric_metering_previous_day_consumption_delivered_watthours",
     "legendFormat": "yesterday"
    },
    {
     "expr": "smart_meter_electric_metering_previous_week_consumption_delivered_watthours",
     "legendFormat": "last week"
    },
    {
     "expr": "smart_meter_electric_metering_previous_month_consumption_delivered_watthours",
     "legendFormat": "last month"
    }
   ]
  },
  {
   "title": "historic gas use",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_gas_metering_previous_day_alternative_consumption_delivered_watthours",
     "legendFormat": "yesterday"
    },
    {
     "expr": "smart_meter_gas_metering_previous_week_alternative_consumption_delivered_watthours",
     "legendFormat": "last week"
    },
    {
     "expr": "smart_meter_gas_metering_previous_month_alternative_consumption_delivered_watthours",
     "legendFormat": "last month"
    }
   ]
  },
  {
   "title": "historic electric cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_electric_prepayment_previous_day_cost_consumption_delivered",
     "legendFormat": "yesterday"
    },
    {
     "expr": "smart_meter_electric_prepayment_previous_week_cost_consumption_delivered",
     "legendFormat": "last week"
    },
    {
     "expr": "smart_meter_electric_prepayment_previous_month_cost_consumption_delivered",
     "legendFormat": "last month"
    }
   ]
  },
  {
   "title": "historic gas cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smart_meter_gas_prepayment_previous_day_cost_consumption_delivered",
     "legendFormat": "yesterday"
    },
    {
     "expr": "smart_meter_gas_prepayment_previous_week_cost_consumption_delivered",
     "legendFormat": "last week"
    },
    {
     "expr": "smart_meter_gas_prepayment_previous_month_cost_consumption_delivered",
     "legendFormat": "last month"
    }
   ]
  },
  { "title": "Power graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Power Use",
   "type": "timeseries",
   "description": "Current Power use in W",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "smart_meter_electric_metering_instantaneous_demand_watts{}",
     "legendFormat": "smart meter"
    }
   ]
  },
  {
   "title": "Electric use per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "increase(smart_meter_electric_metering_current_summation_delivered_watthours_total{}[1d] offset -1d)",
     "legendFormat": "smart meter"
    }
   ]
  },
  {
   "title": "Gas use per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "increase(smart_meter_gas_metering_current_summation_delivered_m3_total{}[1d] offset -1d)",
     "legendFormat": "smart meter"
    }
   ]
  }
 ]
}